### ISSUE TITLE
Generating more Pov-ray objects

### ISSUE THREAD

**Issue by StoicGilgamesh** [guanyingc/TOM-Net_Rendering#1]
First of all Amazing work!

I am also working with transparent objects and came across this amazing work.

I was wondering, how can I generate more pov-ray objects, like you all did like the "object.inc" file?

Some insight would be appreciable.

Best Regards,
Hrishikesh Gupta

**Comment by guanyingc** [comment]
Hi, thanks for the interests.

As mentioned in the paper "We constructed parametric 3D models for the first three cate- gories, and generated a large number of models using ran- dom parameters. For complex shapes, we constructed para- metric 3D models for basic shapes like sweeping-spheres and squashed surface of revolution (SOR) parts, and com- posed a larger number of models using these basic shapes. We generated 178K 3D models in total, with each model as- signed a random refractive index λ ∈ [1.3, 1.5]. ".

You can define some shape templates, and write a simple python script to modify the hyper-parameters.
 
However, I think this data generation process is not very accurate. You might check https://cseweb.ucsd.edu//~mkchandraker/pdf/wacv19_transparent.pdf for a more sophisticated data generation.

**Comment by StoicGilgamesh** [comment]
![Rendered with suggested transform](https://user-images.githubusercontent.com/37928485/206199479-5dc0457b-50b8-46be-89f7-96aa4ccbc7d0.jpg)

**Comment by pranftw** [comment]
Hey @guanyingc how can I download the attenuation masks? Thanks.

**Comment by guanyingc** [comment]
Hi, please check the google drive links in https://github.com/guanyingc/TOM-Net#overview.
![image](https://user-images.githubusercontent.com/8651158/233227975-93da0d38-e45f-4f05-a5da-27c7a9a10ea8.png)

**Comment by pranftw** [comment]
Hey @guanyingc, thanks for the reply. However in `download_objects.sh` https://github.com/guanyingc/TOM-Net_Rendering/blob/bee00df08c7ee4497874ce7349e7958b77b73181/download_objects.sh#L3 it's referring to `TOM-Net_Povray_Inc_Objects.tgz`, which isn't available on Google Drive and also the website is down. Could you please let me know how I can access it? Also `TOM-Net_Povray_Inc_Objects.tgz` would contain the attenuation masks right? Thanks!

**Comment by guanyingc** [comment]
The attenuation masks are not in TOM-Net_Povray_Inc_Objects.tgz. This tgz file only contains povray object in .inc format.

 The masks you want will be generated after the povray rendering. 

TOM-Net_Povray_Inc_Objects.tgz can be downloaded in https://pan.baidu.com/s/1RLX5Po8ElceoqWJmg1_aBA?pwd=p3yz. Thanks.

**Comment by pranftw** [comment]
Hey @guanyingc, thanks for the clarification. However, I'm unable to access the Baidu link from India... Could you please upload it on Google Drive? Many thanks and sorry for the troubles! Cheers!

**Comment by guanyingc** [comment]
Hi, the data link in the download script can be access now. http://www.visionlab.cs.hku.hk/data/TOM-Net/

**Comment by pranftw** [comment]
Thanks a lot!!

**Comment by pranftw** [comment]
Thanks a lot!!

**Comment by pranftw** [comment]
Thanks a lot!!
